#!/bin/sh

BREAKCHARS="(){}[],^%$#@\"\";:''|\\"
CONTRIB=/usr/local/Cellar/clojure-contrib/1.2.0/clojure-contrib.jar
CLOJURE=$CLASSPATH:/usr/local/Cellar/clojure/1.3.0/clojure-1.3.0.jar:$CONTRIB:${PWD}

if [ $# -eq 0 ]; then 
  exec rlwrap --remember -c -b $BREAKCHARS -f "$HOME"/.clj_completions java -cp $CLOJURE clojure.main
else
  exec java -cp $CLOJURE clojure.main $1 -- "$@"
fi
