#!/bin/sh

BREAKCHARS="(){}[],^%$#@\"\";:''|\\"
CLOJURE=$CLASSPATH:/usr/local/Cellar/clojure/1.5.1/clojure-1.5.1.jar:${PWD}

if [ $# -eq 0 ]; then
  exec rlwrap --remember -c -b $BREAKCHARS -f "$HOME"/.clj_completions java -cp $CLOJURE clojure.main
else
  exec java -cp $CLOJURE clojure.main $1 -- "$@"
fi
