#!/bin/sh

logs=`pbpaste`
baseUrl=`echo $logs | grep -Eo "rtmpe://[^ ]+\/ " | grep -Eo "[^ ]+"`
path=`echo $logs | grep -Eo "NetStream.Play.Reset \( [^ ]+ \) " | grep -Eo "[a-zA-Z0-9\/-]+.mp4"`
name=`echo $logs | grep -Eo "NetStream.Play.Reset \( [^ ]+ \) " | grep -Eo "[a-zA-Z0-9-]+.mp4"`

rtmpdump -r "$baseUrl$path" -o "$HOME/Desktop/infoq-$name"
